# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'final.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(913, 653)
        Dialog.setAutoFillBackground(False)
        Dialog.setStyleSheet("background-color: rgb(216, 216, 216);")
        Dialog.setWindowFilePath("")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(0, 0, 911, 191))
        self.widget.setStyleSheet("background-color: rgb(170, 85, 255);")
        self.widget.setObjectName("widget")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(760, 30, 93, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(10, 240, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(170, 85, 255);")
        self.label_4.setObjectName("label_4")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 280, 93, 28))
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(20, 360, 351, 271))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(390, 200, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(170, 85, 255);")
        self.label_7.setObjectName("label_7")
        self.tableWidget_2 = QtWidgets.QTableWidget(Dialog)
        self.tableWidget_2.setGeometry(QtCore.QRect(390, 240, 501, 361))
        self.tableWidget_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(4)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(430, 610, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(170, 85, 255);")
        self.label_8.setObjectName("label_8")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(710, 200, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(170, 85, 255);")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(800, 200, 91, 20))
        self.label_11.setStyleSheet("color: rgb(170, 85, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.label_11.setObjectName("label_11")
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(150, 240, 161, 21))
        self.lineEdit_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(540, 610, 91, 20))
        self.label_12.setStyleSheet("color: rgb(170, 85, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.label_12.setObjectName("label_12")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(100, 320, 161, 21))
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 320, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(170, 85, 255);")
        self.label.setObjectName("label")
        self.lineEdit_3 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_3.setGeometry(QtCore.QRect(150, 200, 161, 21))
        self.lineEdit_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(10, 200, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(170, 85, 255);")
        self.label_5.setObjectName("label_5")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "Profile"))
        self.label_4.setText(_translate("Dialog", "Quantity"))
        self.pushButton_2.setText(_translate("Dialog", "Add"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "price"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Amount"))
        self.label_7.setText(_translate("Dialog", "Cart"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Name"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "price"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "quantity"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Total"))
        self.label_8.setText(_translate("Dialog", "Total Price"))
        self.label_10.setText(_translate("Dialog", "Balance"))
        self.label_11.setText(_translate("Dialog", "2000$"))
        self.label_12.setText(_translate("Dialog", "100$"))
        self.label.setText(_translate("Dialog", "search"))
        self.label_5.setText(_translate("Dialog", "product id "))
        self.loaddata()
        self.pushButton_2.clicked.connect(self.add)
    def loaddata(self):
        people =[{"name":"Dell","price":45,"amount":"50"},{"name":"hp","price":10,"amount":"100"},{"name":"oppo","price":100,"amount":"50"}
        ,{"name":"screen","price":10,"amount":"50"},{"name":"buttery","price":5,"amount":"50"},
        {"name":"DC_charge","price":57,"amount":"50"}
        ]
        self.tableWidget.setRowCount(len(people))
        row =0
        for person in people :
            self.tableWidget.setItem(row,0, QtWidgets.QTableWidgetItem(person["name"]))
            self.tableWidget.setItem(row,1, QtWidgets.QTableWidgetItem(str(person["price"])))
            self.tableWidget.setItem(row,2, QtWidgets.QTableWidgetItem(str(person["amount"])))
            row =row+1
    def add (self):
        people =[{"name":"Dell","price":45,"amount":"50"},{"name":"hp","price":10,"amount":"100"},{"name":"oppo","price":100,"amount":"50"}
        ,{"name":"screen","price":10,"amount":"50"},{"name":"buttery","price":5,"amount":"50"},
        {"name":"DC_charge","price":57,"amount":"50"}]
        x = int(self.lineEdit_3.text())-1
        y = int(self.lineEdit_2.text())
        z = len(people)
        print(people[x])
        list=[people[x]]
        print(list)
        self.tableWidget_2.setRowCount(40)
        jar =self.tableWidget_2.item(0,0)
        s=self.tableWidget_2.item(0,0)
        if self.tableWidget_2.item(0,0)==None :
            row =0
        elif self.tableWidget_2.item(1,0)==None:
            row =1
        elif self.tableWidget_2.item(2,0)==None:
            row =2
        elif self.tableWidget_2.item(3,0)==None:
            row =3
        elif self.tableWidget_2.item(4,0)==None:
            row =4
        elif self.tableWidget_2.item(5,0)==None:
            row =5
        elif self.tableWidget_2.item(6,0)==None:
            row =6
        elif self.tableWidget_2.item(7,0)==None:
            row =7
        elif self.tableWidget_2.item(8,0)==None:
            row =8
        elif self.tableWidget_2.item(9,0)==None:
            row =9
        elif self.tableWidget_2.item(10,0)==None:
            row =10
        elif self.tableWidget_2.item(11,0)==None:
            row =11
        elif self.tableWidget_2.item(12,0)==None:
            row =12
        elif self.tableWidget_2.item(13,0)==None:
            row =13
        elif self.tableWidget_2.item(14,0)==None:
            row =14
        elif self.tableWidget_2.item(15,0)==None:
            row =15
        elif self.tableWidget_2.item(16,0)==None:
            row =16
        elif self.tableWidget_2.item(17,0)==None:
            row =17
        elif self.tableWidget_2.item(18,0)==None:
            row =18
        elif self.tableWidget_2.item(19,0)==None:
            row =19
        elif self.tableWidget_2.item(20,0)==None:
            row =20
        elif self.tableWidget_2.item(21,0)==None:
            row =21
        elif self.tableWidget_2.item(22,0)==None:
            row =22
        elif self.tableWidget_2.item(23,0)==None:
            row =23
        for person in list :
            self.tableWidget_2.setItem(row,0, QtWidgets.QTableWidgetItem(person["name"]))
            self.tableWidget_2.setItem(row,1, QtWidgets.QTableWidgetItem(str(person["price"])))
            self.tableWidget_2.setItem(row,2, QtWidgets.QTableWidgetItem(str(y)))
            self.tableWidget_2.setItem(row,3, QtWidgets.QTableWidgetItem(str(person["price"]*y)))
        result = 0
        for row in self.tableWidget_2.item(row,3):
            result = result + int(self.tableWidget_2.item(row,3).text())
        print(result)








if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
